#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
#
# Type-check the vhci(4) sources against real FreeBSD kernel headers on a
# non-FreeBSD development machine.  This is not a build: nothing is linked
# and no object is usable.  It exists to catch wrong struct members and
# wrong function signatures without a round trip to the test machine.
#
# Requires a FreeBSD source checkout; point FREEBSD_SRC at it.
#
#	tools/syntax-check.sh
#	FREEBSD_SRC=/usr/src tools/syntax-check.sh

set -e

FREEBSD_SRC=${FREEBSD_SRC:-$HOME/work/freebsd-src}
S=$FREEBSD_SRC/sys
V=$(cd "$(dirname "$0")/../sys/dev/vhci" && pwd)
B=${TMPDIR:-/tmp}/vhci-syntax

if [ ! -d "$S/dev/usb" ]; then
	echo "$0: no FreeBSD sys tree at $S" >&2
	echo "clone it with:" >&2
	echo "  git clone --depth 1 -b stable/14 --filter=blob:none --sparse \\" >&2
	echo "      https://git.FreeBSD.org/src.git $FREEBSD_SRC" >&2
	echo "  cd $FREEBSD_SRC && git sparse-checkout set sys" >&2
	exit 1
fi

rm -rf "$B"
mkdir -p "$B"
cd "$B"

# The kernel is built -nostdinc; supply what the compiler's own headers
# and contrib/ck expect.
ln -sf "$S/amd64/include" machine
ln -sf "$S/x86/include" x86
echo '#include <sys/limits.h>' > limits.h
echo '#include <sys/stdint.h>' > stdint.h

# kobj interface headers, normally generated by the kernel build.
for m in "$S/kern/bus_if.m" "$S/kern/device_if.m" "$S/dev/usb/usb_if.m"; do
	awk -f "$S/tools/makeobjops.awk" "$m" -h
done

for o in opt_bus.h opt_usb.h opt_global.h opt_ddb.h opt_usb_debug.h; do
	: > "$o"
done

CC=${CC:-cc}
G=$($CC -print-file-name=include)
status=0

for f in vhci.c vhci_roothub.c vhci_hcd.c; do
	[ -f "$V/$f" ] || continue
	printf '%s: ' "$f"
	if $CC -fsyntax-only -nostdinc -fno-builtin -D_KERNEL -DKLD_MODULE \
	    -std=gnu99 -Wall -Wno-unused-parameter -Wno-pointer-sign \
	    -include opt_global.h \
	    -isystem "$G" -I. -I"$V" -I"$S" -I"$S/contrib/ck/include" \
	    "$V/$f" 2> "$B/$f.log"; then
		echo ok
	else
		echo FAILED
		grep -v '^In file\|note:\|^\s*|\|^\s*+++\|^\s*[0-9]* |' \
		    "$B/$f.log" >&2 || true
		status=1
	fi
done

exit $status
